
package com.epam.entities;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryPort", targetNamespace = "libraryService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryPort {


    /**
     * 
     * @param searchGenresRequest
     * @return
     *     returns com.epam.entities.SearchGenresResponse
     */
    @WebMethod
    @WebResult(name = "searchGenresResponse", targetNamespace = "libraryService", partName = "searchGenresResponse")
    public SearchGenresResponse searchGenres(
        @WebParam(name = "searchGenresRequest", targetNamespace = "libraryService", partName = "searchGenresRequest")
        SearchGenresRequest searchGenresRequest);

    /**
     * 
     * @param getAuthorRequest
     * @return
     *     returns com.epam.entities.GetAuthorResponse
     */
    @WebMethod
    @WebResult(name = "getAuthorResponse", targetNamespace = "libraryService", partName = "getAuthorResponse")
    public GetAuthorResponse getAuthor(
        @WebParam(name = "getAuthorRequest", targetNamespace = "libraryService", partName = "getAuthorRequest")
        GetAuthorRequest getAuthorRequest);

    /**
     * 
     * @param updateGenreRequest
     * @return
     *     returns com.epam.entities.UpdateGenreResponse
     */
    @WebMethod
    @WebResult(name = "updateGenreResponse", targetNamespace = "libraryService", partName = "updateGenreResponse")
    public UpdateGenreResponse updateGenre(
        @WebParam(name = "updateGenreRequest", targetNamespace = "libraryService", partName = "updateGenreRequest")
        UpdateGenreRequest updateGenreRequest);

    /**
     * 
     * @param deleteBookRequest
     * @return
     *     returns com.epam.entities.DeleteBookResponse
     */
    @WebMethod
    @WebResult(name = "deleteBookResponse", targetNamespace = "libraryService", partName = "deleteBookResponse")
    public DeleteBookResponse deleteBook(
        @WebParam(name = "deleteBookRequest", targetNamespace = "libraryService", partName = "deleteBookRequest")
        DeleteBookRequest deleteBookRequest);

    /**
     * 
     * @param searchAuthorsRequest
     * @return
     *     returns com.epam.entities.SearchAuthorsResponse
     */
    @WebMethod
    @WebResult(name = "searchAuthorsResponse", targetNamespace = "libraryService", partName = "searchAuthorsResponse")
    public SearchAuthorsResponse searchAuthors(
        @WebParam(name = "searchAuthorsRequest", targetNamespace = "libraryService", partName = "searchAuthorsRequest")
        SearchAuthorsRequest searchAuthorsRequest);

    /**
     * 
     * @param deleteAuthorRequest
     * @return
     *     returns com.epam.entities.DeleteAuthorResponse
     */
    @WebMethod
    @WebResult(name = "deleteAuthorResponse", targetNamespace = "libraryService", partName = "deleteAuthorResponse")
    public DeleteAuthorResponse deleteAuthor(
        @WebParam(name = "deleteAuthorRequest", targetNamespace = "libraryService", partName = "deleteAuthorRequest")
        DeleteAuthorRequest deleteAuthorRequest);

    /**
     * 
     * @param getGenresRequest
     * @return
     *     returns com.epam.entities.GetGenresResponse
     */
    @WebMethod
    @WebResult(name = "getGenresResponse", targetNamespace = "libraryService", partName = "getGenresResponse")
    public GetGenresResponse getGenres(
        @WebParam(name = "getGenresRequest", targetNamespace = "libraryService", partName = "getGenresRequest")
        GetGenresRequest getGenresRequest);

    /**
     * 
     * @param getBookRequest
     * @return
     *     returns com.epam.entities.GetBookResponse
     */
    @WebMethod
    @WebResult(name = "getBookResponse", targetNamespace = "libraryService", partName = "getBookResponse")
    public GetBookResponse getBook(
        @WebParam(name = "getBookRequest", targetNamespace = "libraryService", partName = "getBookRequest")
        GetBookRequest getBookRequest);

    /**
     * 
     * @param getBooksByAuthorAndGenreRequest
     * @return
     *     returns com.epam.entities.GetBooksByAuthorAndGenreResponse
     */
    @WebMethod
    @WebResult(name = "getBooksByAuthorAndGenreResponse", targetNamespace = "libraryService", partName = "getBooksByAuthorAndGenreResponse")
    public GetBooksByAuthorAndGenreResponse getBooksByAuthorAndGenre(
        @WebParam(name = "getBooksByAuthorAndGenreRequest", targetNamespace = "libraryService", partName = "getBooksByAuthorAndGenreRequest")
        GetBooksByAuthorAndGenreRequest getBooksByAuthorAndGenreRequest);

    /**
     * 
     * @param getAuthorByBookRequest
     * @return
     *     returns com.epam.entities.GetAuthorByBookResponse
     */
    @WebMethod
    @WebResult(name = "getAuthorByBookResponse", targetNamespace = "libraryService", partName = "getAuthorByBookResponse")
    public GetAuthorByBookResponse getAuthorByBook(
        @WebParam(name = "getAuthorByBookRequest", targetNamespace = "libraryService", partName = "getAuthorByBookRequest")
        GetAuthorByBookRequest getAuthorByBookRequest);

    /**
     * 
     * @param getGenresByAuthorRequest
     * @return
     *     returns com.epam.entities.GetGenresByAuthorResponse
     */
    @WebMethod
    @WebResult(name = "getGenresByAuthorResponse", targetNamespace = "libraryService", partName = "getGenresByAuthorResponse")
    public GetGenresByAuthorResponse getGenresByAuthor(
        @WebParam(name = "getGenresByAuthorRequest", targetNamespace = "libraryService", partName = "getGenresByAuthorRequest")
        GetGenresByAuthorRequest getGenresByAuthorRequest);

    /**
     * 
     * @param createBookRequest
     * @return
     *     returns com.epam.entities.CreateBookResponse
     */
    @WebMethod
    @WebResult(name = "createBookResponse", targetNamespace = "libraryService", partName = "createBookResponse")
    public CreateBookResponse createBook(
        @WebParam(name = "createBookRequest", targetNamespace = "libraryService", partName = "createBookRequest")
        CreateBookRequest createBookRequest);

    /**
     * 
     * @param createAuthorRequest
     * @return
     *     returns com.epam.entities.CreateAuthorResponse
     */
    @WebMethod
    @WebResult(name = "createAuthorResponse", targetNamespace = "libraryService", partName = "createAuthorResponse")
    public CreateAuthorResponse createAuthor(
        @WebParam(name = "createAuthorRequest", targetNamespace = "libraryService", partName = "createAuthorRequest")
        CreateAuthorRequest createAuthorRequest);

    /**
     * 
     * @param getGenreRequest
     * @return
     *     returns com.epam.entities.GetGenreResponse
     */
    @WebMethod
    @WebResult(name = "getGenreResponse", targetNamespace = "libraryService", partName = "getGenreResponse")
    public GetGenreResponse getGenre(
        @WebParam(name = "getGenreRequest", targetNamespace = "libraryService", partName = "getGenreRequest")
        GetGenreRequest getGenreRequest);

    /**
     * 
     * @param getAuthorsByGenreRequest
     * @return
     *     returns com.epam.entities.GetAuthorsByGenreResponse
     */
    @WebMethod
    @WebResult(name = "getAuthorsByGenreResponse", targetNamespace = "libraryService", partName = "getAuthorsByGenreResponse")
    public GetAuthorsByGenreResponse getAuthorsByGenre(
        @WebParam(name = "getAuthorsByGenreRequest", targetNamespace = "libraryService", partName = "getAuthorsByGenreRequest")
        GetAuthorsByGenreRequest getAuthorsByGenreRequest);

    /**
     * 
     * @param getGenreByBookRequest
     * @return
     *     returns com.epam.entities.GetGenreByBookResponse
     */
    @WebMethod
    @WebResult(name = "getGenreByBookResponse", targetNamespace = "libraryService", partName = "getGenreByBookResponse")
    public GetGenreByBookResponse getGenreByBook(
        @WebParam(name = "getGenreByBookRequest", targetNamespace = "libraryService", partName = "getGenreByBookRequest")
        GetGenreByBookRequest getGenreByBookRequest);

    /**
     * 
     * @param updateAuthorRequest
     * @return
     *     returns com.epam.entities.UpdateAuthorResponse
     */
    @WebMethod
    @WebResult(name = "updateAuthorResponse", targetNamespace = "libraryService", partName = "updateAuthorResponse")
    public UpdateAuthorResponse updateAuthor(
        @WebParam(name = "updateAuthorRequest", targetNamespace = "libraryService", partName = "updateAuthorRequest")
        UpdateAuthorRequest updateAuthorRequest);

    /**
     * 
     * @param searchBooksRequest
     * @return
     *     returns com.epam.entities.SearchBooksResponse
     */
    @WebMethod
    @WebResult(name = "searchBooksResponse", targetNamespace = "libraryService", partName = "searchBooksResponse")
    public SearchBooksResponse searchBooks(
        @WebParam(name = "searchBooksRequest", targetNamespace = "libraryService", partName = "searchBooksRequest")
        SearchBooksRequest searchBooksRequest);

    /**
     * 
     * @param updateBookRequest
     * @return
     *     returns com.epam.entities.UpdateBookResponse
     */
    @WebMethod
    @WebResult(name = "updateBookResponse", targetNamespace = "libraryService", partName = "updateBookResponse")
    public UpdateBookResponse updateBook(
        @WebParam(name = "updateBookRequest", targetNamespace = "libraryService", partName = "updateBookRequest")
        UpdateBookRequest updateBookRequest);

    /**
     * 
     * @param deleteGenreRequest
     * @return
     *     returns com.epam.entities.DeleteGenreResponse
     */
    @WebMethod
    @WebResult(name = "deleteGenreResponse", targetNamespace = "libraryService", partName = "deleteGenreResponse")
    public DeleteGenreResponse deleteGenre(
        @WebParam(name = "deleteGenreRequest", targetNamespace = "libraryService", partName = "deleteGenreRequest")
        DeleteGenreRequest deleteGenreRequest);

    /**
     * 
     * @param getBooksByAuthorRequest
     * @return
     *     returns com.epam.entities.GetBooksByAuthorResponse
     */
    @WebMethod
    @WebResult(name = "getBooksByAuthorResponse", targetNamespace = "libraryService", partName = "getBooksByAuthorResponse")
    public GetBooksByAuthorResponse getBooksByAuthor(
        @WebParam(name = "getBooksByAuthorRequest", targetNamespace = "libraryService", partName = "getBooksByAuthorRequest")
        GetBooksByAuthorRequest getBooksByAuthorRequest);

    /**
     * 
     * @param getBooksRequest
     * @return
     *     returns com.epam.entities.GetBooksResponse
     */
    @WebMethod
    @WebResult(name = "getBooksResponse", targetNamespace = "libraryService", partName = "getBooksResponse")
    public GetBooksResponse getBooks(
        @WebParam(name = "getBooksRequest", targetNamespace = "libraryService", partName = "getBooksRequest")
        GetBooksRequest getBooksRequest);

    /**
     * 
     * @param getAuthorsRequest
     * @return
     *     returns com.epam.entities.GetAuthorsResponse
     */
    @WebMethod
    @WebResult(name = "getAuthorsResponse", targetNamespace = "libraryService", partName = "getAuthorsResponse")
    public GetAuthorsResponse getAuthors(
        @WebParam(name = "getAuthorsRequest", targetNamespace = "libraryService", partName = "getAuthorsRequest")
        GetAuthorsRequest getAuthorsRequest);

    /**
     * 
     * @param createGenreRequest
     * @return
     *     returns com.epam.entities.CreateGenreResponse
     */
    @WebMethod
    @WebResult(name = "createGenreResponse", targetNamespace = "libraryService", partName = "createGenreResponse")
    public CreateGenreResponse createGenre(
        @WebParam(name = "createGenreRequest", targetNamespace = "libraryService", partName = "createGenreRequest")
        CreateGenreRequest createGenreRequest);

    /**
     * 
     * @param getBooksByGenreRequest
     * @return
     *     returns com.epam.entities.GetBooksByGenreResponse
     */
    @WebMethod
    @WebResult(name = "getBooksByGenreResponse", targetNamespace = "libraryService", partName = "getBooksByGenreResponse")
    public GetBooksByGenreResponse getBooksByGenre(
        @WebParam(name = "getBooksByGenreRequest", targetNamespace = "libraryService", partName = "getBooksByGenreRequest")
        GetBooksByGenreRequest getBooksByGenreRequest);

}
